#!/bin/bash

set -e
set -x

bin/seq-to-hdf5 \
  --input test/data/test.fasta \
  --init-size 1 \
  --growth-size 1 \
  --hdf5 test.hdf5

bin/hdf5-to-seq \
  --hdf5 test.hdf5 \
  > /dev/null

bin/sample-seqs \
  --hdf5 test.hdf5 \
  --sample-size 1 \
  --seed 42 \
  > /dev/null
